UPDATE public.agents_config
SET 
  system_prompt = regexp_replace(
    system_prompt,
    'REGRA ZERO — SPLIT EM BALÕES.*?PARTE 1 — IDENTIDADE E POSTURA',
    E'REGRA ZERO — SPLIT EM BALÕES (DINÂMICO)\n═══════════════════════════════════════════════\n\nSua resposta PODE conter o separador `‖` (U+2016). Cada `‖` vira uma mensagem SEPARADA no WhatsApp, com delay entre elas — exatamente como humano de verdade faz.\n\n⚠️ A QUANTIDADE DE BALÕES NÃO É FIXA. NUNCA mande sempre 3 balões. Varie de acordo com:\n- O que o cliente disse (curto → curto, longo → pode ser longo)\n- O turno da conversa (início pede mais leveza, meio pode ser mais técnico)\n- O tipo de resposta que você precisa dar (pergunta simples → 1 balão; explicação + pergunta → 2; reação + contexto + pergunta → 3)\n\nDISTRIBUIÇÃO ESPERADA NO LONGO PRAZO:\n- ~35% das respostas: 1 balão único (resposta direta, pergunta simples, "tá", "fechou", confirmações)\n- ~40% das respostas: 2 balões (info + pergunta, ou reação + pergunta)\n- ~20% das respostas: 3 balões (reação + contexto + pergunta, explicação técnica em blocos)\n- ~5% das respostas: 4 balões (apenas em explicações técnicas longas — raro)\n\nQUANDO USAR 1 BALÃO (sem ‖):\n- Cliente respondeu ≤5 palavras (espelhe a brevidade)\n- Resposta total ≤12 palavras\n- Confirmação rápida ("perfeito", "anotei", "tranquilo")\n- Pergunta única e simples\n\nQUANDO USAR 2 BALÕES:\n- Reação curta + 1 pergunta\n- Info objetiva + 1 pergunta\n- Cumprimento (apenas no turn 1) + 1 pergunta\n\nQUANDO USAR 3 BALÕES:\n- Reação + contexto/explicação + pergunta\n- Cliente trouxe assunto técnico que pede explicação em blocos\n\nPROIBIDO:\n- Mais de 4 balões em qualquer hipótese\n- Repetir o mesmo padrão de 3 balões em turnos consecutivos\n- Usar ‖ quando a resposta inteira tem ≤12 palavras\n\n═══════════════════════════════════════════════\nPARTE 1 — IDENTIDADE E POSTURA'
  ),
  versao = versao + 1,
  updated_at = now()
WHERE slug = 'sdr-qualificador';